### ISSUE TITLE
Recommended light in activity definitions

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1389] opened 2021-01-04 03:06 UTC
If possible, could recommended light be added back to activity definitions? We lost it with Beyond Light

**Comment by jshaffstall-bng** [comment] 2021-01-05 23:22
Weird! Filed as TFS 967959.

**Comment by Achronos-BNG** [comment] 2021-01-07 23:26
I located the cause of this problem and submitted a fix.  Should arrive later this month.  I also removed the old "activityLevel" field from the json contract since it is meaningless with the current way things work.  Now there will just be "activityLightLevel" which should be what you are looking for.

**Comment by jshaffstall-bng** [comment] 2021-01-19 22:24
This should be fixed now.

**Closed by jshaffstall-bng** 2021-01-19 22:24 UTC
Labels: bug, bug filed
