### ISSUE TITLE
Sony 2 factor auth is broken again

### ISSUE THREAD

**Issue by GreatDaemon** [Bungie-net/api#1242] opened 2020-05-23 22:15 UTC
#897 is happening now again for me for the past week following enabling 2fa on my Sony account.
It's the same issue and same errors as noted previously.
Can I help fix it?

**Comment by jshaffstall-bng** [comment] 2020-06-19 00:24
@GreatDaemon Sorry for the delay! Are you still able to reproduce this issue?

PlayStation sign-in with 2-factor-auth seems to be working for us at the moment.

**Comment by GreatDaemon** [comment] 2020-06-23 00:27
Hey @jshaffstall-bng . Thanks for looking into this. Right now it doesn't. I started using Steam to auth (cross save is awesome). I tried PS auth a week ago and had it happen again.
But - I checked with 2FA disabled on PS side. It may be an issue with Sony's auth where when 2fa is enabled, it doesn't progress the process but sends a prohibited response. My gut feeling is that Sony is releasing internal updates and whenever they do, 2fa auth tokens break a bit for a few days/weeks.

**Comment by jshaffstall-bng** [comment] 2020-06-29 14:38
Thanks for checking. I'm closing this issue but please feel free to file a new issue if this pops up again.

**Closed by jshaffstall-bng** 2020-06-29 14:38 UTC
