### ISSUE TITLE
fastestCompletionMs stat re: raid time

### ISSUE THREAD

**Issue by mistahj67** [Bungie-net/api#132] opened 2017-09-16 18:31 UTC
The fastestCompletionMs stat previously ignored any activities not started from the beginning. 

Though it seems the latest raid fastestCompletionMsmay not filter the same way? 

Additionally I'm curious about the fastestCompletionMs on the crucible gamemodes and if this is updated only on matches started from the beginning or includes those joined mid match.
Thanks!

**Comment by floatingatoll** [comment] 2017-09-17 21:10
Is MatchDurationMs or RaidDurationMs included as a value anywhere that would permit detection of "partials", so to speak?

**Comment by vthornheart-bng** [comment] 2017-09-18 18:55
I'll ask our stats guru - either he or I will get back to you once able!

**Comment by ChaseMalik** [comment] 2017-11-13 05:11
@vthornheart-bng Any updates on this?  It seems this change also impacts the `GetDestinyAggregateActivityStats'` `fastestCompletionMsForActivity` value.  Is it by design that checkpoints are included in the calculation of this value or a bug?  If by design, is it possible to get a fresh equivalent of the value like we had in D1 (similar to the request in #228)?

**Comment by vthornheart-bng** [comment] 2017-11-13 05:53
Bad news I'm afraid - sorry that I forgot to respond earlier!  It turns out that this field no longer exists. :(  I will make a request to have a similar value added - but I don't know if or when it will come about.

**Comment by ChaseMalik** [comment] 2017-11-13 08:43
Sorry... now you've confused me a bit...

`fastestCompletionMsForActivity` is currently returned by both `GetDestinyAggregateActivityStats` and `GetHistoricalStats` - This value includes all instances of the activity (including checkpoints).

`fastestCompletionSecondsForActivity` is the variable that was returned in D1 that returned the fastest time for fresh runs (not including checkpoints) - that variable no longer exists, as near as I can tell

Were you actually referring to the old D1 variable when you said 
> It turns out that this field no longer exists (fastestCompletionMsForActivity)

Because I still see `fastestCompletionMsForActivity` returned

Anyways, it seems as though the important take away is that there isn't a way to get the fastest full run right now... but that you will make a request to have it added... so thanks!

**Comment by vthornheart-bng** [comment] 2017-11-13 15:11
Ah, sorry, I misspoke - fastestCompletionSecondsForActivity is the one I meant to refer to.

**Comment by vthornheart-bng** [comment] 2017-12-08 00:50
I can't promise that this is something I can actually fix in the winter wishlist, particularly if the stats system isn't storing it under the surface or if something is broken with that storage.  But I will try to at least investigate what the situation is so that I know whether it's possible.

**Comment by vthornheart-bng** [comment] 2018-06-20 16:24
It looks like this will be fixed for the July release!  If the starting phase on the raid is not the first one, the activity will stop storing fastest completion.

Note that, unfortunately, there's no way for us to retroactively apply these changes to PGCRs.  But PGCRs from that point forward will have this change.

**Comment by ChaseMalik** [comment] 2018-06-21 07:50
This is awesome!

Couple of quick questions:
1. Just want to confirm that this fixes both this issue (`fastestCompletionMsForActivity` only updated on fresh runs) and #228 (by adding `startingPhaseIndex` or something similar to raid post games)
2. You mentioned that post games won't retroactively be updated, but I'm wondering how the AggregateStats' variable `fastestCompletionMsForActivity` will be handled.  Will the variable be reset, such that it only represents fresh runs that happen after the July release?  Or will players with times from checkpoints keep those times, and only be able to update them if they run a fresh run faster than their current record (which in certain cases is impossible)?

Thanks again.

**Closed** 2018-09-05 18:58 UTC
Labels: enhancement, investigation, ready for release
