### ISSUE TITLE
Determining current faction rally milestone?

### ISSUE THREAD

**Issue by lordmortis** [Bungie-net/api#189] opened 2017-10-01 06:22 UTC
I'm wondering if i'm doing the right thing: 

I'm querying `/Destiny2/Milestones/` to get all the public milestones, and while there's faction rally information in there - it seems to return all the activities/quests for the entire week - i'm not sure how to get the current one? (I'm looking for a milestone with the friendly name of `FactionRally` and inside that it's got all the Activities/Quests for the week - but the first one in the list is EDZ, but today is Nessus (for example) )

**Comment by vthornheart-bng** [comment] 2017-10-14 01:59
Ah yes, this was a bug discovered while I was away - I have not yet had time to investigate the root cause of why this came about.  But I'll be certain to resolve the issue before the next Faction Rally comes around.

**Comment by vthornheart-bng** [comment] 2017-12-06 22:10
Should be fixed now.

**Closed by vthornheart-bng** 2017-12-06 22:10 UTC
Labels: bug
