### ISSUE TITLE
JSON component definitions may have incorrect Access-Control-Allow-Origin header cached

### ISSUE THREAD

**Issue by as-com** [Bungie-net/api#1226] opened 2020-04-08 00:25 UTC
See: https://github.com/DestinyItemManager/DIM/issues/5101

tl;dr: Bungie.net appears to return different Access-Control-Allow-Origin headers based on the referrer of the request to a JSON component definition (`https://www.bungie.net` in some cases and `*` in others). Whoever is first to warm up the Cloudflare cache will set the Access-Control-Allow-Origin header for the rest of the requests to the Cloudflare PoP, leading to unexpected behavior in third-party applications.

**Comment by Achronos-BNG** [comment] 2020-06-04 17:34
This issue is being tracked.  We have a short term workaround for when it happens, but we are investigating the root cause.

**Comment by Achronos-BNG** [comment] 2020-06-08 19:46
I have located two problems in our CORS processor code that seem to be related, one of which likely outright causes this problem and the other is the reason for why it is intermittent.

**Comment by Achronos-BNG** [comment] 2020-06-19 00:54
This should be fixed now.

**Closed by Achronos-BNG** 2020-06-19 00:54 UTC
Labels: bug, bug-filed

**Comment by AndretheG** [comment] 2024-03-02 12:26
I don't believe the issue is fixed. Still having 4 years later :/ I've tried adding * to the Origin Header section in the developer portal in conjunction with both including and excluding an origin header in ALL of my requests. I've tried explicitly listing my domain in the developer portal while also including the origin header in my requests. Nothing seems to work. Only thing I've seen are cachebuster workarounds.
