### ISSUE TITLE
Psychohack has 8 entries instead of 1

### ISSUE THREAD

**Issue by darkelement1987** [Bungie-net/api#1631] opened 2022-03-18 08:15 UTC
![image](https://user-images.githubusercontent.com/21128187/158962237-0302e20b-aa48-4889-8520-f4d82f57d852.png)

Not sure if a bug or intended

**Comment by jshaffstall-bng** [comment] 2022-03-18 16:18
This seems to be a consequence of each 'Throne World' weapon having it's own version of this origin trait (auto rifle, smg, etc.).

Closing this as 'by design'.

**Closed by jshaffstall-bng** 2022-03-18 16:18 UTC
