### ISSUE TITLE
Character Progression shows as private

### ISSUE THREAD

**Issue by lax20attack** [Bungie-net/api#47] opened 2017-09-06 00:33 UTC
User has privacy controls appropriately enabled on Bungie.net. According to the description, this should be returning public data.

https://www.bungie.net/Platform/Destiny2/2/Profile/4611686018428440298/Character/2305843009260343992/?components=202

{"Response":{"progressions":{"privacy":2},"itemComponents":{}},"ErrorCode":1,"ThrottleSeconds":0,"ErrorStatus":"Success","Message":"Ok","MessageData":{}}

**Comment by lax20attack** [comment] 2017-09-06 00:34
I have also heard CharacterActivities (204) is having the same issue but have not verified it myself.

**Comment by vthornheart-bng** [comment] 2017-09-06 00:36
Ah, good find!  I have suspicions as to why this may be occurring.  I will investigate in the coming days.

**Comment by xKairu** [comment] 2017-09-06 01:35
I was the one having issues with 204 in Discord, but I've since worked around the issue:

You have to specify the count, mode and page, or else it returns as if you're set to private.

Working:
`https://www.bungie.net/Platform/Destiny2/2/Account/4611686018452182455/Character/2305843009260713968/Stats/Activities?count=10&mode=0&page=1`

Not working:
`https://www.bungie.net/Platform/Destiny2/2/Account/4611686018452182455/Character/2305843009260713968/Stats/Activities`

**Comment by vthornheart-bng** [comment] 2017-09-06 11:20
Hmm, yes that's unfortunately true: I believe those are required properties for the endpoint, though they're not marked as such.  I'll make note of that and try to add some metadata to that effect (or potentially just give them reasonable defaults, as it does feel a bit odd to have required querystring parameters if there are reasonable defaults to pass)

**Comment by xKairu** [comment] 2017-09-06 23:01
>are you seeing two different problems?

Possibly, I was speaking with lax on Discord about the issue, saw this and figured it'd be the same issue. I'll make a new one, thanks!

**Comment by lax20attack** [comment] 2017-09-07 01:03
Just to add more to this-

I can view EVERYONE's rep when logged in. I can't view anyone's when not logged in.

Working example: 
https://www.destinydashboard.net/#/reputation

It's a javascript app so you can see all of the network requests.

**Comment by vthornheart-bng** [comment] 2017-09-07 01:26
Good info!  Indeed, I have a strong suspicion as to the root cause of this issue.

**Comment by vthornheart-bng** [comment] 2017-09-11 06:15
Just found the root of this problem, I'll push for this to be fixed in the next release.

**Closed** 2017-09-13 18:08 UTC
Labels: bug, for next release
