### ISSUE TITLE
Since beyond light the stat increase icons are blank

### ISSUE THREAD

**Issue by NigelHietala** [Bungie-net/api#1437] opened 2021-03-10 09:43 UTC
for example https://data.destinysets.com/i/SandboxPerk:467553279
These icons are transparent overlays so maybe part of why then ended up white rectangles, is they are now JPEG instead of PNG images?

**Comment by jshaffstall-bng** [comment] 2021-03-16 01:33
Yep, this is a dupe of #1342

**Closed by jshaffstall-bng** 2021-03-16 01:33 UTC
