### ISSUE TITLE
forTitleGilding not set on Triumphs that are for title guilding

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#1408] opened 2021-02-09 18:06 UTC
`forTitleGilding` is not set to true for any Record.

I would expect this triumph to have it https://data.destinysets.com/i/Record:2369658343

**Comment by jshaffstall-bng** [comment] 2021-02-09 23:19
Oops! Filed as TFS 976730, and we'll try to have this fixed with our update on Feb 16.

**Comment by jshaffstall-bng** [comment] 2021-02-10 00:57
It turns out 'gilding' is in fact spelled 'gilding' and not 'guilding', which is the root cause of this bug internally.

It appears you made the same mistake in the title of this issue :P

**Comment by joshhunt** [comment] 2021-02-10 16:12
Not gonna lie, i have no idea what the word is, let alone how to spell it 😅

**Comment by jshaffstall-bng** [comment] 2021-02-16 18:23
This should be fixed with new content now.

**Closed by jshaffstall-bng** 2021-02-16 18:23 UTC
Labels: bug, bug filed
