### ISSUE TITLE
Tracked stats not consistent between endpoints

### ISSUE THREAD

**Issue by adherrling** [Bungie-net/api#92] opened 2017-09-12 16:41 UTC
The endpoint /.../Character/{characterId}/Stats/Activities/ and /.../Character/{characterId}/Stats/ both eventually point to the same response component, namely Destiny.HistoricalStats.DestinyHistoricalStatsValue. However, the actual statistics reported by activity are different between the two endpoints. 

For example, when using the first endpoint to request stats for Control games, using the query string parameter ?mode=control, the number of tracked statistics is only 18, whereas the "allPvP" stat collection from the second endpoint tracks 59 different stats. 

Is there a reason for this discrepancy? In other words, would it be possible for us to retrieve the entire set of tracked stats broken down by activity mode, instead of only a small subset per activity instance and the remainder being aggregated? I believe another issue has already been raised about the empty response at the AggregateActivity statistics endpoint - it is possible that the answer to my question lies in this endpoint, in that the stats won't be reported by instance but rather by aggregated activity mode (instead of the current activity "realm" - that is, all PvP, all strikes, etc., so to speak).

**Comment by vthornheart-bng** [comment] 2017-09-15 03:28
Yes, this is unfortunately true, and by design.  DestinyHistoricalStatsValue is really just the contract for the form in which we return values: the specific values return vary by mode - as well as other factors, such as whether you're filtering for all time vs. daily etc...

The main reason for this is that we have these stats for some modes and not for others, and for some filters but not for others.  That's really all it boils down to.  If you see some that you wish were in mode X,  make a list and post the request here, and we can bring it up to the folks working on the stats backend!

**Comment by vthornheart-bng** [comment] 2017-09-15 03:29
I'm closing this as "wontfix", but if you end up with specific suggestions for stats you wish were being returned for a given mode or mode(s), post those and we'll bring them up as enhancement requests!

**Closed by vthornheart-bng** 2017-09-15 03:29 UTC
Labels: question, wontfix

**Comment by adherrling** [comment] 2017-09-15 19:15
Got it. Thanks for the reply!
