### ISSUE TITLE
CrossSave account is missing D1 data

### ISSUE THREAD

**Issue by brendonshih** [Bungie-net/api#1183] opened 2020-01-06 19:57 UTC
I've been using my PSN account for D1 and D2 since D1 beta. I linked a Battle.net account to my Bungie.net account but when crosssave came, I chose to go with my PSN account. I also linked it to Stadia.

But for some reason, a lot of my data is missing. First of all, no D1 information is loading. When trying to load my raid report on https://d1.raid.report/ps/IceBloo, I'm Getting a 1618 error on two of the calls. First the player search comes back with a valid response:
`{"Response":[{"iconPath":"/img/theme/destiny/icons/icon_psn.png","membershipType":2,"membershipId":"4611686018428806653","displayName":"IceBloo"}],"ErrorCode":1,"ThrottleSeconds":0,"ErrorStatus":"Success","Message":"Ok","MessageData":{}}`

Then the two API calls after that fail:
https://www.bungie.net/d1/Platform/Destiny/Stats/Account/2/4611686018428806653/
`{"ErrorCode":1618,"ThrottleSeconds":0,"ErrorStatus":"DestinyUnexpectedError","Message":"An unexpected error has occurred while trying to grab Destiny information.  Let us know if you see this.","MessageData":{}}`

https://www.bungie.net/d1/Platform/Destiny/2/Account/4611686018428806653/Summary/
`{"ErrorCode":1618,"ThrottleSeconds":0,"ErrorStatus":"DestinyUnexpectedError","Message":"An unexpected error has occurred while trying to grab Destiny information.  Let us know if you see this.","MessageData":{}}`

When I try using wastedondestiny it can't even find any D1 data.

**Comment by vthornheart-bng** [comment] 2020-01-06 21:41
Yes, unfortunately this is likely caused by Stadia account linking.  We are investigating this issue, but I can't give an ETA yet on when we will have a fix!

**Comment by davidc14** [comment] 2020-03-07 15:16
Are there any updates on this?

**Comment by Achronos-BNG** [comment] 2020-03-13 21:10
I am currently testing a fix for this and hope to be able to deploy it soon, assuming that the fix works.

**Comment by dconefourseven** [comment] 2020-03-29 08:36
Posted this in #1151 also. Posting here to maximise coverage.
It seems that linking my account with Twitch, to take advantage of the new official extension, has caused this issue to regress on my account.

**Comment by Achronos-BNG** [comment] 2020-04-20 17:46
Sorry I didn't comment earlier.

I'm going to close this issue as this was for the Stadia.  #1151 is what we'll use tracking the ongoing issue with Twitch credential linking that is similar to this.  The Stadia linking problem should be solved though.

**Closed by Achronos-BNG** 2020-04-20 17:46 UTC
Labels: bug, investigation
