### ISSUE TITLE
GroupV2.GetGroupByName doesn't always work for clans with a space in the name

### ISSUE THREAD

**Issue by maciek134** [Bungie-net/api#162] opened 2017-09-21 20:00 UTC
It works sometimes, but usually behaves like if the clan didn't exist. You can check it here: https://d2clan.klh.io/ and input Bronion Knights.

**Comment by vpzed** [comment] 2017-09-21 20:35
Are you URL encoding the search string?

**Comment by bladefist** [comment] 2017-09-23 22:35
Confirmed, this is a bug.

**Comment by Achronos-BNG** [comment] 2017-10-09 00:05
GetGroupByName does not currently work for clans.  Well, more accurately, it may work for clans that used to be groups before the migration, but generally, it is not reliable.  This issue will be fixed in a future update, likely around the time of the PC release of Destiny 2.

**Closed by Achronos-BNG** 2017-10-09 00:05 UTC
Labels: bug

**Comment by bladefist** [comment] 2017-10-09 01:28
@Achronos-BNG is there another endpoint we should be using or just wait for the fix? Thanks.

**Comment by vpzed** [comment] 2017-10-12 06:16
@Achronos-BNG I would recommend leaving issues Open until the fix has been publically implemented.  Closing an issue will keep most people from seeing it since the default search is for Open and will lead to duplicate issue submissions which wastes valuable Bungie developer time.

Once the issue has been verified as resolved then the issue would be closed.  Then if people are watching the Issue they can know when it is resolved too and can re-test their code.  It's a win-win.
