### ISSUE TITLE
Special characters in GET requests

### ISSUE THREAD

**Issue by jgayfer** [Bungie-net/api#266] opened 2017-10-26 00:17 UTC
I'm running into problems looking for accounts with special characters in their names. 

**Example**
Username: Grëëm#1623
```
https://www.bungie.net/Platform/Destiny2/SearchDestinyPlayer/4/Gr%C3%AB%C3%ABm%231623
```

I'm *pretty* sure I'm encoding this properly, but I may not be. Wondering if anyone here has any suggestions on how I can continue. 

Note that this username is from one of my users, and haven't explicitly confirmed that he has played the game on PC yet, but I am 99.5% sure that he has.

**Comment by vthornheart-bng** [comment] 2017-10-26 00:22
Hmm, interesting!  Yeah, URL Encoding should have done the trick... very interesting.

Could you have them send you a link to their profile page on bungie.net, and then link it here?  That will give us some info.

**Comment by jgayfer** [comment] 2017-10-26 00:32
Here is the link: https://www.bungie.net/en/Profile/254/15187153/Greem

**Comment by vthornheart-bng** [comment] 2017-10-26 00:39
Welp, this is going to be an interesting mystery, I'll have to chase down the root cause but for some reason his name has been encoded according to our search as:

GrÃ«Ã«m#1623

... ugh.

I don't know why yet, so I don't have a workaround I can provide aside from the very specific situation that for some reason umlats are being converted to Ã«... I'll have to get back to you on this once I talk to some folks over here.

**Comment by jgayfer** [comment] 2017-10-26 00:47
Interesting. Thanks for getting back to me promptly! Don't work too hard though, it's getting late here on the west coast ;)

**Comment by vthornheart-bng** [comment] 2017-10-26 00:54
^_^ No prob!  I had to hit up some folks to get more info about potential upstream causes, and I'm not sure when they'll reply... so I might not have more info for a bit unfortunately.  But I'll update here once I get more info.  In the meantime, the hacky thing that comes to my mind is to try and convert the incoming UTF-8 to Windows-1252, this is what I heavily suspect is happening somewhere in our pipeline, so doing that should result in you passing characters that it recognizes for the string matching.   Yuck.  If the problem turns out to be upstream of us, we may end up having to do the same thing to at least start returning responses for these folks.  Fun times... glad you reported this!

**Comment by floatingatoll** [comment] 2017-10-26 03:15
That looks like UTF-8 bytes were not decoded prior to search encoding, such
that the search is receiving raw byte strings of un-decoded UTF-8, rather
than native UTF-8 character strings decoded from the raw bytes in the URI.

On Wed, Oct 25, 2017 at 5:54 PM, Vendal Thornheart <notifications@github.com

**Comment by bladefist** [comment] 2017-10-26 12:17
I'm seeing Chinese/Japanese and other languages that use unicode not working as well. I'm assuming this is the same issue?

**Comment by Tetron-bng** [comment] 2017-10-27 02:00
The display names for Battle.net accounts getting stored in a corrupted state in our database and so search will not be able to find them. A fix is in the works but no ETA.

**Comment by Tetron-bng** [comment] 2017-11-10 00:16
This issue has been resolved.  The user's display name will continue to be garbled until they sign into the game.

**Closed by Tetron-bng** 2017-11-10 00:16 UTC
Labels: bug, investigation
