### ISSUE TITLE
Manifest returning "Classified" as name for some items

### ISSUE THREAD

**Issue by afehners** [Bungie-net/api#86] opened 2017-09-11 10:13 UTC
As well as returning classified it also states "Classified item. Bungie does not yet provide information about this item. Item is not yet transferable."

In most cases I've seen this on my own account it was for items that didn't appear to be particularly special with a mix of Rare and Legendary items. In one case it was for a legendary quest item "Rat King's Crew'.

I'm using the latest version of the Manifest database and observer this issue in my App and in DIM

**Comment by iBotPeaches** [comment] 2017-09-11 11:09
Game designers redact/classify items to prevent data mining. Once they are out in the open, they are usually declassified on next deployment. Leave the hashes here and usually that helps Bungie staff check if the item will be unclassified or not. Also dupe of #67

**Comment by floatingatoll** [comment] 2017-09-11 17:32
Note that "Next deployment" may take up to several weeks, as there are
multiple interlocking systems required to declassify things.

**Comment by vthornheart-bng** [comment] 2017-09-11 18:30
Yes, and a sometimes slow chain of approvals from the people who make the blacklisting decisions.  We're working on improving that process, but it's still a sometimes significant lagtime unfortunately.

**Comment by vthornheart-bng** [comment] 2017-09-11 18:30
I'm going to close this one for now - unfortunately, it's something that we'll work on reducing lag time on over time but we'll never likely get rid of.

**Closed by vthornheart-bng** 2017-09-11 18:30 UTC
