### ISSUE TITLE
Spider materials rotation logic/times 

### ISSUE THREAD

**Issue by michabbb** [Bungie-net/api#663] opened 2018-09-09 09:19 UTC
Hi, I recognized a rotation of materials for exchange in less than 24hrs, now I am confused. How often and when does this change? Thanks.

**Comment by ArkahnX** [comment] 2018-09-09 16:11
Duplicate of #654

**Comment by vthornheart-bng** [comment] 2018-09-09 18:04
Ah, good eye on that.  More info there!

**Closed by vthornheart-bng** 2018-09-09 18:04 UTC
