### ISSUE TITLE
Incorrect contestants modifier on Dares of Eternity: Legend

### ISSUE THREAD

**Issue by unitymind9** [Bungie-net/api#1628] opened 2022-03-16 02:25 UTC
GET
/Destiny2/3/Profile/(my profile ID)/Character/(my warlock ID)/?components=204

```
{
  "activityHash": 1699058902,
...
  "modifierHashes": [
      2301442403,
      939324719,
      3859784314,
      3886813791,
      3649753063,
      3362074814,
      1914961422,
      1626706410
  ],
...
}
```

In-game modifier says this week's boss is Crota, but I can get Zydron modifier. (3886813791)

**Comment by jshaffstall-bng** [comment] 2022-03-21 20:39
Related to #1602 and caused by incorrect activity modifier definition generation.

This should be fixed with new content tomorrow morning.

**Closed** 2022-04-15 17:19 UTC
Labels: bug, bug filed
