### ISSUE TITLE
DestinyUnhandledException for various Stats endpoint calls on some accounts/activity modes

### ISSUE THREAD

**Issue by migit128** [Bungie-net/api#638] opened 2018-09-04 21:26 UTC
For some people, it doesnt matter how many times you retry, it will never work.  Alex is an example of this:

http://destinydevs.github.io/BungieNetPlatform/docs/API-Test#/Destiny2/GetHistoricalStatsForAccount/p:membershipType=4,destinyMembershipId=4611686018467250482/q:groups=0

I believe he was banned from comp, but thats the only thing that i can think of that makes him unique.

**Comment by migit128** [comment] 2018-09-04 21:28
I havent been able to get my database to update in over 24 hours now.  Do you know when things will be back to normal?

**Comment by vthornheart-bng** [comment] 2018-09-04 21:32
We are currently experiencing increased latency to the game servers as a result of the massive increase in traffic both to the game and the API, as well as latency around the one-time upgrade to the current game version.  To protect the integrity of the game servers, we are throttled as a result, which any users of the API will experience.  Generally, the upgrade-related latency and timeouts tend to subside within a day or two from a major release, which should relieve the main source of this issue.

**Comment by floatingatoll** [comment] 2018-09-04 21:35
Alternate, shorter, unofficial answer:

If it's a launch day (D2 ahoy), a patch day (Forsaken today), a
beta-test day (such as Gambit this weekend), or if login queues are
active (such as today), then all API consumers should plan on the API
being down for 24-48 hours.

**Comment by migit128** [comment] 2018-09-04 21:37
But why do specific users just not work?  You'd think it'd work eventually, but it doesnt seem to matter how many times I request this specific persons information.  It just fails every single time!

**Comment by floatingatoll** [comment] 2018-09-04 21:39
For your specific outage example, database sharding of 50 million active
players at peak capacity would absolutely lead to a scenario where some
users are inaccessible and others are fine.

**Comment by vthornheart-bng** [comment] 2018-09-04 21:40
Aye, and that is - for all intents and purposes - what's occurring right now unfortunately.

**Comment by migit128** [comment] 2018-09-04 21:47
sigh... My stuff is designed for an all or nothing update, so I'm completely screwed for now.

**Comment by floatingatoll** [comment] 2018-09-04 22:27
It’ll be okay! Everyone gets used to it after a while and it’s just part of launch days: Play Destiny Actual, rather than Helper Apps Anything :)

**Comment by migit128** [comment] 2018-09-05 17:13
I have been playing destiny, but the thing is, the automation automates things that I now need to do instead of playing destiny.

Things still don't work.

**Comment by vthornheart-bng** [comment] 2018-09-05 17:27
I'll give it a look, thanks for the link and info!

**Comment by vthornheart-bng** [comment] 2018-09-05 17:51
Logged as TFS 706827 to investigate, I need to determine whether this is launch server latency/throttling related, or if there's something else happening.

**Comment by migit128** [comment] 2018-09-05 18:47
Thanks!

**Comment by migit128** [comment] 2018-09-06 18:02
Any updates? 

I got some data on this....  The "GetHistoricalStatsForAccount" call succeeded for 160 people in my clan and failed for the other 373 people.  That's almost exactly 30% of users that it works for.

For now I've got to disable the "get deleted characters" method.  Hopefully I've been a good little programmer and designed things properly so the scripts that use the data from my db work with > 3 characters per account... Hopefully the loader will recover itself once these 1618 errors are resolved...

My discord is an absolute mess atm and I need my db to update...

**Comment by floatingatoll** [comment] 2018-09-06 18:06
Could you select a random member of the 373 group for Bungie to inspect
more closely — and/or, Can you provide the response header Set-Cookie value
`bungled=...` for one of the 373 failures?

**Comment by vthornheart-bng** [comment] 2018-09-06 18:10
We will not be able to deploy a fix for this until 9/12, which is our next scheduled hotfix - but I will let you know once that's ready to roll!

**Comment by migit128** [comment] 2018-09-06 19:13
ok.  i've patched my stuff enough so it works for people in my clan so this isn't quite as bad anymore.    The 1000 people in my discord that aren't in my clan wont have their roles though... Not as big of a deal.

**Comment by migit128** [comment] 2018-09-06 19:35
discord roles.  part of the reason i'm hitting the api and loading the data in my own db as a cache is so i can have roles in my discord that show how many raid clears people have, what their KD is, and what division they are in.  there are other scripts that act on the data in the db as well to report on players activity in the game, hand out high activity roles, create a list of people who do not meet our activity requirements, and more!

**Comment by vthornheart-bng** [comment] 2018-09-06 23:41
After further investigation, I found out that this and #633 unfortunately have different root causes.  I was able to fix that (and thus, to fix Activity History that requests Gambit as a subset) for 9/12, but the root cause of this issue you're seeing looks to unfortunately be happening on a deeper level than Bungie.net itself: it's going to require a fix for the game servers.  I've reported it up to the folks who work on that system, but I don't have an ETA yet of when they'll be able to deploy it: their deployment cadence and deadlines for when a fix must be in and verified before it can ship are much more stringent than the Bungie.Net side, so it may be a bit longer before we have a real fix for this.

I'll give you an ETA when I can.  I apologize for the outages.

**Comment by migit128** [comment] 2018-09-07 00:16
Yikes.... guess I need to stop polling for deleted characters everywhere for now.

**Comment by vthornheart-bng** [comment] 2018-09-07 00:31
Aye.  Sorry for the interruption this is causing you - at first it sounded like the symptoms of game server throttling that we were seeing in other systems, but it's definitely not the case.  It appears to be fairly intermittent in terms of who actually is affected: potentially due to some specific activities that they've played: but I'm not certain of the specifics that can cause a character's aggregate history to end up in this state.  I hope to get more info when they're able to do further analysis.

**Comment by vthornheart-bng** [comment] 2018-09-07 02:45
Okay, looks like they've been given a release window of September 18th for the game-side fixes for this.  Once we get those, we should be good to go.  Sorry about that - looks like it'll be a little longer of a wait, but not as long as I was fearing.

**Closed** 2018-09-19 18:44 UTC
Labels: bug, bug-filed, investigation, ready for release
