### ISSUE TITLE
Feature Request: Items Tracked for Collections

### ISSUE THREAD

**Issue by Jakosaur** [Bungie-net/api#559] opened 2018-07-10 18:19 UTC
Suggestion: See what items have been tracked, ready for Collections in September per account? Just thought I'd ask/suggest a feature.

Thanks

**Comment by vthornheart-bng** [comment] 2018-07-10 18:42
I'm thinking the same thing!  I'm actually looking into that as we speak as part of my work on Forsaken, seeing if there's a good way to merge it in early if there's a way to do so that won't distract us too much from the other work we have to do ASAP.  But we have to be careful, it's going to involve a somewhat sensitive ad-hoc merging of data between two different versions of game content, and I don't want to freak anyone out about false positives/false negatives, and I can't take much in the way of testing resources away from the other more immediate work we ahve to do.  It's a feature that I think people will like, but also one that could freak people out if it shows the wrong info.

I'll see what can be done, but because of those risks above I can't make any promises!

**Comment by vthornheart-bng** [comment] 2018-07-24 20:30
I did a little hacking a couple weekends ago and put together a janky way for us to expose such a checklist.  This should be going live this coming wednesday.

There'll be two checklists: one that's profile-wide and one that has per-character info.

An important thing to know is that, because Collections will supersede and provide more data in every way, I'm going to make these two checklists go away when Forsaken goes live - so it's only going to live for a short time, and then it will disappear from the data.

Profile checklist hash: 3393554306
Character checklist hash: 3246761912

The contracts themselves will not change.  The definitions for these items will have a name, description, icon, and itemHash and that's it!

Another thing to note is that this data is going to come with a few important caveats:

1) The hoops I had to jump through to combine this data was unusual for our standard worfklow, and with other Forsaken work we didn't have the time to vet this data thoroughly.  There may be bugs, potentially both from the way I combined the data and due to the fact that this new Collections data itself is still in testing - I had the Collections team give it a once over and it looks good to them, but I will not be surprised if we find occasional items having issues.  I figure that having the majority of the data will be more useful for people than not having any, even if some ends up having minor issues.  Consider this data to be "experimental" (because, indeed, it is highly experimental and working with content that isn't even complete yet)

2) Not all Solstice of Heroes data may come through, because not all of that data had yet been integrated into the Collections data (which meant that I didn't have a "source of truth" to work with).  Be assured that, if items don't appear, **they're still being tracked**: they just weren't yet codified in the Collections data by the time we kicked our build that will be going live.

3) Redacted items will not appear in this checklist.

**Comment by ArkahnX** [comment] 2018-07-24 23:52
For some clarification, should this data be expected to contain items warmind and before, but just might be missing some of the items that will be coming out with solstice of heroes?

Secondary question, if old items are not present in this checklist, should we assume they aren't tracked and hold on to them?

**Comment by vthornheart-bng** [comment] 2018-07-25 00:06
Yes - it'll contain items from warmind and before, and *some* Solstice of Heroes items... but I can't guarantee that it will be all of them.

If you end up seeing any old items that aren't present in the checklist, let me know here (file an issue) and I'll look into it!  If old items aren't present, it is most likely because they're redacted in our content (but still being tracked).  However, if you do end up seeing any definitely shoot an issue over here so I can find out for sure.

**Comment by ArkahnX** [comment] 2018-07-25 00:08
Thanks for letting me know! I'm mostly curious about these weird items I have like level 1 armor, the original white ghost shell, etc. Though I bet those are out of scope for collections

**Comment by vthornheart-bng** [comment] 2018-07-25 21:22
I'll leave this bug open for now in case anyone runs into issues with the content!

**Comment by vthornheart-bng** [comment] 2018-07-25 23:20
Ah!  I did a little looking, and it looks like these were also items that didn't yet have entries in the yet-to-be-released Forsaken Collections data, which meant when I joined it to current content I didn't see it as a collectible and thus it isn't being returned yet.

I did double check though, and indeed they all *are* being tracked, so no fear there!  But they just hadn't been wired up as actual "Collectibles" in the new content yet.  The next time we do a full deployment on BNet, I'll refresh it with the latest Collectibles data, which should bring more of these in.

**Comment by vthornheart-bng** [comment] 2018-07-25 23:50
One more update here - current known items that aren't being returned.  These *ARE* confirmed as being tracked, they just weren't in the Forsaken side of the data yet as of the time that we published these Collectibles checklists to BNet:

* Many of the latest Iron Banner items
* Many of the latest Faction items
* Some Solstice of Heroes items

The reason why is somewhat interesting - those who work on software will appreciate it.  The content is in different "branches": different partitions of content so that people can work on, say, Solstice of Heroes while other people can work on Forsaken without them interfering with each other.  To prevent destabilizing other people working in other branches, the content gets pulled up and integrated at regular intervals, and then has to be integrated with whatever new features might be using that content.  So before newer items like the latest Iron Banner or other event items will end up in Forsaken data, someone has to do that work to "integrate" the new items into Forsaken's content, and then add them to the new Collections definitions.  That work is quite literally happening as we speak (how exciting!), so as a result we don't have it yet in our own checklists.  But they *are* being tracked in your profile/character state.

**Comment by vthornheart-bng** [comment] 2018-07-26 17:16
^_^ Glad it is useful!

**Comment by Skully0074** [comment] 2018-07-27 17:33
I see items with blue checkmarks, are these items that were deleted before Warmind (May 8th) and will not be in our collections come September?

**Comment by Jakosaur** [comment] 2018-07-27 17:35
If you’re on about DestinySets, Blue Checkmarks are items that will be in Collections come Forsaken/September.

On 27 Jul 2018, at 18:33, Skully0074 <notifications@github.com<mailto:notifications@github.com>> wrote:


I see items with blue checkmarks, are these items that were deleted before Warmind (May 8th) and will not be in our collections come September?

**Comment by Skully0074** [comment] 2018-07-27 21:51
Thanks for the link finding alot of useful info there.

**Comment by jamie1192** [comment] 2018-08-13 06:27
I was going to open a separate issue but figured it might be more appropriate to post it in this thread..

is the response format for checklists going to change or will it output as it currently does once Forsaken drops?
Dynamic object names are considered very bad practice on their own, let alone having dynamically named objects with dynamically named keys inside them making it damn near impossible to do any sort of databinding with the response.

The current output - 

    "checklists": {
        "2348765377": {
            "12343432": false,
            "387638736": true.
            ...
        },
        "2360931290": {
		"2920200623": false,
		"1533707526": false,
                ...
        },
        ...
    }

Would it be possible to get it changed to something like this for example?

    "checklists": {
        "2955980198": [{  
            "hash": "1940327752"
            "isCompleted": true
        }, {
            "hash": "2195137425"
            "isCompleted": false
        }, {
        ..etc 
        }],
        "2360931290": [{
            "hash": "2920200623"
            "isCompleted": true
        }, {
           "hash": "2286037801"
           "isCompleted": true
        }]

        ...etc
    }

Still stuck with dynamically named objects with this idea but at least then it makes it slightly more manageable having an arraylist to databind and iterate through..

**Comment by vthornheart-bng** [comment] 2018-08-13 17:26
The format of the response won't be changing: these objects are intended to serialize/deserialize as dictionaries: which is admittedly less convenient in some languages than others, but we're going to stick with this format for the foreseeable future.

**Comment by danhawk911** [comment] 2018-08-14 21:10
So should I be worried that it does not show the fwc bone grip with a blue check mark? I know I accidentally deleted it way after the warming expansion came out but I don’t see it coming up on the tracker as having it already. :-(

**Comment by vthornheart-bng** [comment] 2018-08-14 21:42
What's the specific name of that item?  I couldn't find one with that name, so I wasn't able to check on it.

**Comment by danhawk911** [comment] 2018-08-14 21:48
Bonegrip is the name of the ship for psn use danhawk

**Comment by danhawk911** [comment] 2018-08-14 22:00
https://db.destinytracker.com/d2/en/items/2924982631-bonegrip

**Comment by vthornheart-bng** [comment] 2018-08-14 22:07
Interesting!  I took a look, and sure enough they *are* being tracked as of Warmind, so you should be set - but for some reason that item didn't end up coming down in our checklists.  There must be a bug in the janky process I mentioned above to create the Checklist that affected this item for some particular reason (my guess is that the item's been miscategorized in some way such that I was excluding it), but unfortunately we don't have a release window to put out a new Checklist before Forsaken goes live.

What I do see however is that the item is indeed being tracked, so as long as you had it after Warmind went live you should be good to go!

**Comment by danhawk911** [comment] 2018-08-15 00:40
The only thing I’ve notice where the new monarchy weapons are the same as the ship🤷‍♀️ But iam like 99.99% sure I got them. But I am just glad I can buy the iron banner armor so I can compete the Titan. Thank you all for you support

**Comment by vthornheart-bng** [comment] 2018-08-15 00:45
No problem, glad to be of help!

**Comment by danhawk911** [comment] 2018-08-21 20:56
Is the minuet-42 handcanon not showing up for other people on the tracker?

**Comment by Adnan008** [comment] 2018-08-23 22:29
minuet-42 shows up as collected, i also have a question, is "Traitor's Fate" sword shows up as collected? because i have digital deluxe and it doesn't show this as collected

**Comment by andy3865683** [comment] 2018-08-25 01:00
I'm wondering if my Adjudicator is tracked because it was while back and know its not tracked so can u plz help?

**Closed** 2018-09-05 18:58 UTC
Labels: enhancement, ready for release
