### ISSUE TITLE
[Question] - No way to get Xur's inventory?

### ISSUE THREAD

**Issue by jgayfer** [Bungie-net/api#152] opened 2017-09-19 18:49 UTC
I've read a few comments about vendors not being available, but on the other hand I've seen other third party apps reporting his wares. Is it possible to get his inventory at this point in time?

Follow up question. I'm not entirely sure how the vendor endpoints will work. I'm not quite sure why a characterID is needed in the request, since many vendors offer the same items to everyone. Am I misunderstanding how vendors work?

**Comment by vthornheart-bng** [comment] 2017-09-19 19:01
Unfortunately, the ones reporting his wares are almost certainly populating it manually: we don't have any way to get his inventory "canonically" yet.

Indeed, the character ID is a frustrating but important limitation of accessing Vendors: a character ID is needed in the request because a Vendor's wares can be (and for most vendors, they are) dependent on the character browsing them.

This is not true for Xur by design, but as a rule this is true for vendors: and indeed, at any time if the designers decide to do so, Xur could be changed to give entirely different wares depending on who is looking at him.  In Destiny 1 we had an endpoint specifically for Xur because we relied on this assumption of Xur's inventory being the same for everyone, and we will likely do it again: but if for some reason the designers decide to chuck the notion of one Xur inventory for all out the window, we'll have to throw out that service as well.  I hope that never comes to pass, but just as a heads up any character-independent Xur endpoint we expose will be based on an assumption on our part rather than something set in stone.

**Comment by vthornheart-bng** [comment] 2017-09-19 19:01
I'll close this for now, let me know if you have any follow up questions!

**Closed by vthornheart-bng** 2017-09-19 19:01 UTC
Labels: question

**Comment by jgayfer** [comment] 2017-09-20 22:44
Thanks for the response! 

Is there a single place where I can find a summary of updates such as new endpoints becoming available and such? Would be ideal if I could be notified of such changes.
