### ISSUE TITLE
PGCR startingPhaseIndex always returns 0

### ISSUE THREAD

**Issue by BlazeBoss17** [Bungie-net/api#1320] opened 2020-11-12 17:29 UTC
After the beyond light update, startingPhaseIndex in PGCR always returns as 0, regardless of what checkpoint an activity actually starts at. For example, shattered throne (referenceId=2032534090) used to have startingPhaseIndex from 0-14. Now always returns 0.

Same thing for last wish, garden of salvation, pit of heresy, and others probably. instanceId=7169308700 is a garden of salvation that should have startingPhaseIndex=7, but it is 0.

Without this information, it is impossible to determine if an instance was started from the beginning or boss checkpoint, which is functionality I use heavily.

**Comment by jshaffstall-bng** [comment] 2020-11-13 16:02
Thanks for the report! This is filed as TFS 958060.

**Comment by StormTester** [comment] 2021-01-26 13:01
Just wondering, what's the feasibility and likeliness that the fix for this will retroactively correct PGCRs that are affected by this issue and if there's any update or ETA for this fix?

**Comment by Achronos-BNG** [comment] 2021-04-12 18:32
It is highly unlikely that a fix for this will be retroactive.  The problem is that the way activities work substantially changed with Beyond Light, and one of the casualties of it was that the phase index is not "a thing" as it was before.  The data is simply not there any more.  However, as a fix for this problem, in an upcoming release, we will be able to add a new field that will let you know if the activity was started from the beginning, which will take the place of this field in functionality.  This fix should probably be in by the next season, unless something comes up with it that proves to be a problem.

**Comment by Achronos-BNG** [comment] 2021-05-24 18:02
It did not get in this release, sorry.

**Comment by BlazeBoss17** [comment] 2021-05-24 18:14
Is the new field still planned for an upcoming release? Any update on the timeline (next season, next yearly expansion)?

**Comment by Achronos-BNG** [comment] 2021-12-03 01:13
A fix for this is currently scheduled to go live with the release of Witch Queen.  I'll probably add a new field (a boolean), but I can also wire it up so that the old field (startingPhaseIndex) is only 0 when the activity was started from the beginning (matching the inverse of the boolean, which is something like "startedFromTheBeginning")

**Comment by D217696** [comment] 2021-12-07 03:02
> A fix for this is currently scheduled to go live with the release of Witch Queen. I'll probably add a new field (a boolean), but I can also wire it up so that the old field (startingPhaseIndex) is only 0 when the activity was started from the beginning (matching the inverse of the boolean, which is something like "startedFromTheBeginning")

Is there any chance we could get this field added to the GetActivityHistory endpoint, when it's available?

**Comment by Achronos-BNG** [comment] 2021-12-08 22:59
The new field will be along side the existing startingPhaseIndex field in the PGCR.  Adding it to other places would be a different issue, and probably outside the scope of this particular item.

**Comment by TorKallon** [comment] 2022-01-12 01:04
If an activity has a cutscene at the beginning and people load into a
checkpoint that is immediately after the cutscene, what value will the
boolean have? With startingPhaseIndex we could account for situations like
that and still give people credit for a complete run even if they
accidentally used a checkpoint that avoided the cutscene.

**Comment by Achronos-BNG** [comment] 2022-02-23 22:58
startingPhaseIndex is not supported anymore, and only reflects the value of activityWasStartedFromTheBeginning now, which means exactly what it says (if you start from a checkpoint, you didn't start the activity from the beginning, as I understand how it is implemented).

**Closed by Achronos-BNG** 2022-02-23 22:58 UTC
Labels: bug, bug filed

**Comment by floatingatoll** [comment] 2022-03-09 00:03
Does the above "not supported" comment apply to #1619 as well?

**Comment by justrealmilk** [comment] 2022-03-11 07:10
> Does the above "not supported" comment apply to #1619 as well?

Why would it when the other raids provide
