### ISSUE TITLE
Transferring items to characters using API returns in repeated in-game "Triumph completed" toasts

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#644] opened 2018-09-05 03:02 UTC
Whenever i transfer gear to my _other_ characters, which I have not yet logged in since Tuesday's 2.0.1 patch, I the game shows "Triumph completed" toast notifications at the bottom of the screen. This happens multiple times.

The notifications look like they're for completing lost sectors, one for each destination. Transferring multiple items results in duplicate toasts.

Video https://youtu.be/XMzRCqaJC_E

**Comment by vthornheart-bng** [comment] 2018-09-05 17:57
Bringing this up with some folks now.

**Comment by joshhunt** [comment] 2018-09-08 12:29
For what it's worth, today I started playing Forsaken on my Hunter alt and this still happens when I transfer items from my Warlock (which has now completed Forsaken campaign) to my Hunter.

**Comment by ckhicks** [comment] 2018-09-11 14:40
Same here on all counts - tons of in-game notifications when this happens.

**Comment by designker** [comment] 2018-10-10 12:28
Is there any news on if this is going to be fixed? I get daily mails about it

**Comment by vthornheart-bng** [comment] 2018-10-10 17:11
I've heard nothing since my initial report.  Hang tight, I will try to get an update.

**Comment by vthornheart-bng** [comment] 2018-10-10 17:19
Ah, well that's part of the problem.  I had messaged someone, but never formally made a bug.  I had been told this was being investigated, but I'm not sure what that progress is - I've made a new bug and will try to pass that around to folks in order to find out what's up.

TFS 721517

**Comment by floatingatoll** [comment] 2018-10-15 19:02
For diagnostic purposes, this issues occurs even when the other two
characters have never logged into Destiny 2 at all (imported from D1).

**Comment by vthornheart-bng** [comment] 2018-11-01 22:52
Just an update on this - indeed, we aren't going to have a game-side fix for this in the near future unfortunately.  They're working on a fix, but it's targeted for early in the new year.  I apologize to anyone experiencing this issue: we've got no good workaround aside from the painful one recommended above by @ericleone.

**Comment by ckhicks** [comment] 2018-11-05 16:15
I'm still seeing this at least once a night, but it's just a mild annoyance. Thanks!

**Comment by vthornheart-bng** [comment] 2018-11-11 22:20
For anyone looking at this issue, I spoke a little bit on Reddit about what's happening - it's pretty interesting!  Here's the scoop:

So to understand what's happening here, the first thing that's important is that many parts of the game - such as the triggers that activate Triumph "toast" messages - are activated as the result of some internal state crossing a numerical threshold. This internal state can be stored in a variety of places, but the most common two are on your Account (thus accessible across all characters) and on each of your characters separately.

Sometimes, this state is updated by checking and aggregating the values from many other states. This check and aggregation tends to happen when the values in question change, as well as during certain transition periods such as log in, log out, or when your data is accessed via the API (as part of a process that is also checking for whether your daily/weekly/etc... resets should be getting run).

In the case of lost sectors, there's a bunch of (for lack of a better word) "flags" that indicate whether you've ever found those sectors. There's also a single state that's counting how many of those flags are set. The bug here is that those flags being counted are on your character, and the single state counting how many are set are on your account.

When you perform a transfer that interacts with a character that's not the one you have logged in and are actively playing the game, these counts run: but they run under the context of the not logged-in character. This updates the account-stored value being used to determine whether the threshold has been crossed to show the Triumphs toast messages.

For a more concrete example: Let's say you need 5 and on your logged-in Titan you've done all 5, but on your Hunter you only have 2. If you interact with your Hunter through the API while logged into your Titan, those counts run - but because they're erroneously mixing character and account-level state, they're re-counting in the context of the hunter. The count state on your account gets updated to 2. Now, the next time that count is performed on the Titan - if you go to orbit, or if you then transfer an item using the API from the vault to the Titan - the count gets run again in the context of the Titan and the count goes back to 5. The threshold is crossed, and the game launches the "Triumphs" toast.

So when you see that message coming up, that's what's happening under the hood - and why the workaround is effective. If you go find all the lost sectors with all your characters, the count never falls under the threshold: so even though it's being re-evaluated, it no longer triggers the Triumphs toast!

**Comment by floatingatoll** [comment] 2018-11-11 22:38
To ask an odd question: Is this related to why flying into the Tower triggers "Lost Sector Discovered" in-game sometimes too?

**Comment by vthornheart-bng** [comment] 2018-11-11 23:09
If it's happening after you transfer an item from a not-logged-in character to your vault, indeed it is!

**Comment by rentalhost** [comment] 2019-01-27 19:16
Without news?

Sometimes the same message pops on screen, once for each item transfered. A possible workaround is ignore all repeated messages in each character session. Is it possible?

**Comment by floatingatoll** [comment] 2019-02-05 01:34
Hi, this came up on Reddit a couple times recently. The general tone seems to be “Will this ever be fixed?”; while I don’t endorse that phrasing, duly noted (and if someday you find that this will _not_ be fixed, please do let us know).

**Comment by vthornheart-bng** [comment] 2019-04-16 19:47
This should be fixed up as of a few weeks ago!

**Closed by vthornheart-bng** 2019-04-16 19:47 UTC
Labels: bug, bug-filed, investigation

**Comment by Forge64** [comment] 2019-11-12 00:28
Good news everyone! It's back! Same conditions to trigger as before. Same symptoms "TRIUMPH: Lost Sectors completed: Titan" and so on. Please reopen/open bug as appropriate, as this is a regression corresponding to roughly Shadowkeep release time frame.

**Comment by vthornheart-bng** [comment] 2019-11-12 02:08
Yes, we're tracking this after getting some reports on Reddit about it a few days ago.  The introduction of Interval Triumphs apparently caused a break in the prior fix.  A fix is checked in, but unfortunately it required a game-side change.  We won't be seeing the change actually go live until the game's winter release, so sometime in December.  Bummer.
